import streamlit as st
import os
from dotenv import load_dotenv

# Set wide layout FIRST
st.set_page_config(page_title="Zero Click Analytics", layout="wide", initial_sidebar_state="expanded")

import data_ingestion
import data_cleaning
import data_analysis
import kpi_generator
import visualization
import ml_engine
import forecasting
import insights
import chatbot
import dashboard

# Load ENV
load_dotenv()

def initialize_state():
    if 'logged_in' not in st.session_state:
        st.session_state.logged_in = False
    if 'registered_users' not in st.session_state:
        st.session_state.registered_users = {"admin": "admin"}
    if 'current_file_id' not in st.session_state:
        st.session_state.current_file_id = None
        st.session_state.df = None
        st.session_state.cleaned_df = None
        st.session_state.kpis = None
        st.session_state.charts = None
        st.session_state.ml_results = None
        st.session_state.forecast = None
        st.session_state.insights = None
        st.session_state.column_types = None
        st.session_state.stats = None
        st.session_state.correlations = None

def login_page():
    st.markdown("<br><br>", unsafe_allow_html=True)
    st.markdown("<h1 style='text-align: center; color: #7367f0;'>Zero Click Analytics</h1>", unsafe_allow_html=True)
    st.markdown("<h4 style='text-align: center; color: #6c757d; margin-bottom: 30px;'>The Intelligent Data Operating System</h4>", unsafe_allow_html=True)
    
    col1, col2, col3 = st.columns([1, 1.2, 1])
    with col2:
        with st.container():
            tabs = st.tabs(["Login", "Sign Up"])
            
            with tabs[0]:
                st.markdown("### Login Account")
                st.markdown("---")
                log_user = st.text_input("Username", key="log_user", placeholder="Enter your username")
                log_pass = st.text_input("Password", type="password", key="log_pass", placeholder="Enter your password")
                submit_log = st.button("Login", use_container_width=True, type="primary")
                
                if submit_log:
                    if log_user in st.session_state.registered_users and st.session_state.registered_users[log_user] == log_pass:
                        st.session_state.logged_in = True
                        st.success("Logged in successfully!")
                        st.rerun()
                    else:
                        st.error("Invalid credentials. Please try again.")

            with tabs[1]:
                st.markdown("### Create an Account")
                st.markdown("---")
                reg_user = st.text_input("New Username", key="reg_user", placeholder="Choose a username")
                reg_pass = st.text_input("Password", type="password", key="reg_pass", placeholder="Choose a password")
                reg_pass_conf = st.text_input("Confirm Password", type="password", key="reg_pass_conf", placeholder="Repeat password")
                submit_reg = st.button("Sign Up", use_container_width=True, type="primary")
                
                if submit_reg:
                    if not reg_user or not reg_pass:
                        st.warning("Please fill in all fields.")
                    elif reg_pass != reg_pass_conf:
                        st.error("Passwords do not match.")
                    elif reg_user in st.session_state.registered_users:
                        st.error("Username already exists. Please choose another one.")
                    else:
                        st.session_state.registered_users[reg_user] = reg_pass
                        st.success("Account created successfully! You can now log in.")

def about_page():
    st.markdown("<br>", unsafe_allow_html=True)
    st.title("ℹ️ About Zero Click Analytics")
    st.markdown("---")
    st.markdown("""
    Welcome to **Zero Click Analytics**, the modern data operating system designed to automate tedious data processing tasks and deliver clear insights instantly. 
    
    ### 🌟 Core Capabilities
    - **Automated Data Processing**: Effortlessly upload CSV or Excel files.
    - **Smart Auto-Cleaning**: Missing value imputation, formatting correction, and outlier treatment out-of-the-box.
    - **AI-Powered Insights**: Get clear, contextual business recommendations generated by Gemini AI.
    - **Auto ML & Time Series Forecasting**: One-click exploratory machine learning to uncover key drivers, and dynamic Prophet forecasting for any detectable time-series data.
    - **Interactive & Beautiful Dashboards**: Every result is packaged into a premium, executive-level dashboard interface.
    
    ### 🛡️ Security / Disclaimer
    This application is designed for prototype exploration. Always review the data processing logic and AI insights before making critical business decisions.
    
    ### 💻 System Information
    - Version: `1.0.0`
    - Main Technologies: Streamlit, Pandas, Plotly, Scikit-Learn, Prophet, Google GenAI.
    """)

def dashboard_page():
    st.title("⚡ Zero Click Analytics")
    st.markdown("<h4 style='color: #7367f0; margin-top: -15px; margin-bottom: 20px; font-weight: 600;'>Executive Dashboard Interface</h4>", unsafe_allow_html=True)
    st.write("Upload any CSV or Excel file and get instant cleaning, ML models, vibrant KPIs, and AI insights—completely automatically.")
    
    uploaded_file = st.file_uploader("Drop your dataset here (CSV, Excel)", type=['csv', 'xlsx', 'xls'])
    
    if uploaded_file is not None:
        file_id = f"{uploaded_file.name}-{uploaded_file.size}"
        
        # Only process if new file
        if st.session_state.current_file_id != file_id:
            st.session_state.current_file_id = file_id
            # Reset chat
            st.session_state.chat_history = []
            
            with st.spinner("Processing Dataset (Data Loading & Cleaning)..."):
                try:
                    df = data_ingestion.load_file(uploaded_file)
                    st.session_state.df = df
                    if df is not None:
                        cleaned_df = data_cleaning.clean_data(df)
                        st.session_state.cleaned_df = cleaned_df
                except Exception as e:
                    st.error(f"Error in data ingestion/cleaning: {e}")
                    return

            if st.session_state.cleaned_df is not None:
                with st.spinner("Analyzing Columns & Stats..."):
                    try:
                        c_types = data_analysis.get_column_types(st.session_state.cleaned_df)
                        stats = data_analysis.compute_stats(st.session_state.cleaned_df)
                        corrs = data_analysis.find_correlations(st.session_state.cleaned_df)
                        st.session_state.column_types = c_types
                        st.session_state.stats = stats
                        st.session_state.correlations = corrs
                    except Exception as e:
                        st.error(f"Error in analysis: {e}")
                        
                with st.spinner("Generating KPIs..."):
                    try:
                        kpis = kpi_generator.generate_kpis(st.session_state.cleaned_df, st.session_state.column_types)
                        st.session_state.kpis = kpis
                    except Exception as e:
                        st.error(f"Error in KPI generation: {e}")

                with st.spinner("Creating Visualizations..."):
                    try:
                        charts = visualization.auto_charts(st.session_state.cleaned_df, st.session_state.column_types)
                        st.session_state.charts = charts
                    except Exception as e:
                        st.error(f"Error in charts generation: {e}")

                with st.spinner("Testing ML Opportunities..."):
                    try:
                        ml_res = ml_engine.auto_ml(st.session_state.cleaned_df, st.session_state.column_types)
                        st.session_state.ml_results = ml_res
                    except Exception as e:
                        st.error(f"Error running ML: {e}")
                
                with st.spinner("Checking for Time Series Forecasts..."):
                    try:
                        fc = forecasting.auto_forecast(st.session_state.cleaned_df, st.session_state.column_types)
                        st.session_state.forecast = fc
                    except Exception as e:
                        st.error(f"Error running Prophet forecasting: {e}")

                with st.spinner("Fetching AI Insights from Gemini..."):
                    try:
                        ins = insights.generate_insights(
                            st.session_state.cleaned_df, 
                            st.session_state.stats, 
                            st.session_state.correlations
                        )
                        st.session_state.insights = ins
                    except Exception as e:
                        st.error(f"Error fetching AI insights: {e}")

        # Render Dashboard if processed successfully
        if st.session_state.cleaned_df is not None:
            # Wrap chat callback
            def chat_cb(query):
                return chatbot.chat_response(query, st.session_state.cleaned_df, st.session_state.column_types)
                
            try:
                dashboard.render_dashboard(
                    st.session_state.df,
                    st.session_state.cleaned_df,
                    st.session_state.kpis,
                    st.session_state.charts,
                    st.session_state.ml_results,
                    st.session_state.forecast,
                    st.session_state.insights,
                    chat_cb
                )
            except Exception as e:
                st.error(f"Dashboard render error: {e}")

def main():
    initialize_state()
    
    if not st.session_state.logged_in:
        login_page()
    else:
        st.sidebar.markdown("### 🧭 Main Navigation")
        page = st.sidebar.radio("Go to", ["Dashboard", "About"], label_visibility="collapsed")
        
        st.sidebar.markdown("---")
        
        if st.sidebar.button("Logout 🚪", use_container_width=True):
            st.session_state.logged_in = False
            st.rerun()

        if page == "Dashboard":
            dashboard_page()
        elif page == "About":
            about_page()

if __name__ == "__main__":
    main()
